<?php

return array(
    'login@process'=>array(
        'email'=>array('type'=>'email','opt'=>false),
        'password'=>array('type'=>'password','opt'=>false)
    ),
    'register@process'=>array(
        'firstName'=>array('type'=>'text','opt'=>false),
        'lastName'=>array('type'=>'text','opt'=>false),
        'emailAddress'=>array('type'=>'email','opt'=>false),
        'password'=>array('type'=>'password','opt'=>false),
        'confirmPassword'=>array('type'=>'password','opt'=>false),
        'dateOfBirth'=>array('type'=>'datetime','opt'=>false),
        'phoneNumber'=>array('type'=>'phone','opt'=>false),
        'address'=>array('type'=>'text','opt'=>false)
    ),
    'contact@process'=>array(
        'name'=>array('type'=>'text','opt'=>false),
        'subject'=>array('type'=>'text','opt'=>false),
        'message'=>array('type'=>'text','opt'=>false)
    ),
    'discount@create'=>array(
        'discountFactor'=>array('type'=>'range','opt'=>false)
    ),
    'discount@edit'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'discount@delete'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'discount@process'=>array(
        'id'=>array('type'=>'integer','opt'=>false),
        'factor'=>array('type'=>'range','opt'=>false),
        'used'=>array('type'=>'checkbox','opt'=>false)
    ),
    'booking@fetchAvailableTrips'=>array(
        'location'=>array('type'=>'integer','opt'=>false),
        'date'=>array('type'=>'date','opt'=>false),
        'time'=>array('type'=>'time','opt'=>false)
    ),
    'booking@process'=>array(
        'location'=>array('type'=>'integer','opt'=>false),
        'date'=>array('type'=>'date','opt'=>false),
        'time'=>array('type'=>'time','opt'=>false),
        'trips'=>array('type'=>'integer','opt'=>false),
        'persons'=>array('type'=>'integer','opt'=>false),
        'discount'=>array('type'=>'integer','opt'=>true)
    ),
    'bus@create'=>array(
        'nrSeats'=>array('type'=>'integer','opt'=>false)
    ),
    'bus@delete'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'bus@edit'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'bus@process'=>array(
        'nrSeats'=>array('type'=>'integer','opt'=>false),
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'location@create'=>array(
        'name'=>array('type'=>'text','opt'=>false),
        'longitude'=>array('type'=>'range','opt'=>true),
        'latitude'=>array('type'=>'range','opt'=>true)
    ),
    'location@delete'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'location@edit'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'location@process'=>array(
        'id'=>array('type'=>'integer','opt'=>false),
        'name'=>array('type'=>'text','opt'=>false),
        'longitude'=>array('type'=>'range','opt'=>true),
        'latitude'=>array('type'=>'range','opt'=>true)
    ),
    'trip@create'=>array(
        'busId'=>array('type'=>'integer','opt'=>false),
        'departureId'=>array('type'=>'integer','opt'=>false),
        'arrivalId'=>array('type'=>'integer','opt'=>false),
        'dateTimeStart'=>array('type'=>'datetime','opt'=>false),
        'dateTimeEnd'=>array('type'=>'datetime','opt'=>false)
    ),
    'trip@delete'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'trip@edit'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'trip@process'=>array(
        'id'=>array('type'=>'integer','opt'=>false),
        'busId'=>array('type'=>'integer','opt'=>false),
        'departureId'=>array('type'=>'integer','opt'=>false),
        'arrivalId'=>array('type'=>'integer','opt'=>false),
        'dateTimeStart'=>array('type'=>'datetime','opt'=>false),
        'dateTimeEnd'=>array('type'=>'datetime','opt'=>false)
    ),
    'reset@send'=>array(
        'email'=>array('type'=>'email','opt'=>false)
    ),
    'reset@process'=>array(
        'password'=>array('type'=>'password','opt'=>false),
        'confirmPassword'=>array('type'=>'password','opt'=>false)
    ),
    'tickets@generate'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'user@promote'=>array(
        'id'=>array('type'=>'integer','opt'=>false)
    ),
    'profile@submit'=>array(
        'firstName'=>array('type'=>'text','opt'=>false),
        'lastName'=>array('type'=>'text','opt'=>false),
        'password'=>array('type'=>'password','opt'=>false),
        'dateOfBirth'=>array('type'=>'datetime','opt'=>false),
        'phoneNumber'=>array('type'=>'phone','opt'=>false),
        'address'=>array('type'=>'text','opt'=>false)
    ),
    'home@fetchWeather'=>array(
        'city'=>array('type'=>'text','opt'=>false)
    )
);